"""Add schemas related to github integration

Revision ID: 31cc86c908ca
Revises: 94588da62828
Create Date: 2025-11-11 23:34:44.660915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31cc86c908ca'
down_revision: Union[str, None] = '94588da62828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
syncstatusenum = sa.Enum('IDLE', 'SYNCING', 'FAILED', 'COMPLETED', name='syncstatusenum')
syncstepenum = sa.Enum('NONE', 'REPOS', 'ISSUES', 'COMMITS', name='syncstepenum')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    syncstatusenum.create(op.get_bind(), checkfirst=False)
    syncstepenum.create(op.get_bind(), checkfirst=False)
    op.create_table('github_repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_profile_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('stargazers_count', sa.Integer(), nullable=True),
    sa.Column('forks_count', sa.Integer(), nullable=True),
    sa.Column('is_fork', sa.Boolean(), nullable=True),
    sa.Column('repo_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repo_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_commit_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['external_profile_id'], ['external_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repositories_github_repo_id'), 'github_repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_github_repositories_id'), 'github_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_github_repositories_language'), 'github_repositories', ['language'], unique=False)
    op.create_table('github_commits',
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('external_profile_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['external_profile_id'], ['external_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['github_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sha')
    )
    op.create_index(op.f('ix_github_commits_authored_at'), 'github_commits', ['authored_at'], unique=False)
    op.create_index(op.f('ix_github_commits_sha'), 'github_commits', ['sha'], unique=False)
    op.create_table('github_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_profile_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('github_issue_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('issue_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['external_profile_id'], ['external_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['github_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_issues_github_issue_id'), 'github_issues', ['github_issue_id'], unique=True)
    op.create_index(op.f('ix_github_issues_id'), 'github_issues', ['id'], unique=False)
    op.add_column('external_profiles', sa.Column('external_id', sa.Integer(), nullable=False))
    op.add_column('external_profiles', sa.Column('external_username', sa.String(), nullable=True))
    op.add_column('external_profiles', sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('external_profiles', sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('external_profiles', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('external_profiles', sa.Column('sync_status', sa.Enum('IDLE', 'SYNCING', 'FAILED', 'COMPLETED', name='syncstatusenum'), nullable=False))
    op.add_column('external_profiles', sa.Column('sync_step', sa.Enum('NONE', 'REPOS', 'ISSUES', 'COMMITS', name='syncstepenum'), nullable=False))
    op.add_column('external_profiles', sa.Column('last_sync_error', sa.String(), nullable=True))
    op.add_column('external_profiles', sa.Column('last_sync_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_external_profiles_sync_status'), 'external_profiles', ['sync_status'], unique=False)
    op.drop_column('external_profiles', 'platform_id')
    op.drop_column('external_profiles', 'profile_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_profiles', sa.Column('profile_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('external_profiles', sa.Column('platform_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_external_profiles_sync_status'), table_name='external_profiles')
    op.drop_column('external_profiles', 'last_sync_attempt_at')
    op.drop_column('external_profiles', 'last_sync_error')
    op.drop_column('external_profiles', 'sync_step')
    op.drop_column('external_profiles', 'sync_status')
    op.drop_column('external_profiles', 'last_synced_at')
    op.drop_column('external_profiles', 'refresh_token_expires_at')
    op.drop_column('external_profiles', 'access_token_expires_at')
    op.drop_column('external_profiles', 'external_username')
    op.drop_column('external_profiles', 'external_id')
    op.drop_index(op.f('ix_github_issues_id'), table_name='github_issues')
    op.drop_index(op.f('ix_github_issues_github_issue_id'), table_name='github_issues')
    op.drop_table('github_issues')
    op.drop_index(op.f('ix_github_commits_sha'), table_name='github_commits')
    op.drop_index(op.f('ix_github_commits_authored_at'), table_name='github_commits')
    op.drop_table('github_commits')
    op.drop_index(op.f('ix_github_repositories_language'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_github_repo_id'), table_name='github_repositories')
    op.drop_table('github_repositories')
    syncstatusenum.drop(op.get_bind(), checkfirst=False)
    syncstepenum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
