"""Add fields in GithubCommit

Revision ID: deb06b345f2b
Revises: ff9fc252c15e
Create Date: 2026-01-22 08:07:13.765740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb06b345f2b'
down_revision: Union[str, None] = 'ff9fc252c15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

significance_enum = sa.Enum(
    'FEATURE',
    'REFACTOR',
    'CHORE',
    'NOISE',
    name='significancelevel',
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    significance_enum.create(op.get_bind(), checkfirst=False)
    op.add_column('github_commits', sa.Column('significance_score', sa.Float(), nullable=True))
    op.add_column('github_commits', sa.Column('significance_classification', sa.Enum('FEATURE', 'REFACTOR', 'CHORE', 'NOISE', name='significancelevel'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_commits', 'significance_classification')
    op.drop_column('github_commits', 'significance_score')
    # ### end Alembic commands ###
