"""Add fields in User

Revision ID: e770355d5b73
Revises: 5cf71efa231f
Create Date: 2026-05-09 17:55:29.251322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e770355d5b73'
down_revision: Union[str, None] = '5cf71efa231f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('headline', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_blob', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('media_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'media_type')
    op.drop_column('users', 'avatar_blob')
    op.drop_column('users', 'headline')
    # ### end Alembic commands ###
