"""Add schemas related to timeline

Revision ID: ff9fc252c15e
Revises: 31cc86c908ca
Create Date: 2025-12-17 08:00:44.995528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9fc252c15e'
down_revision: Union[str, None] = '31cc86c908ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('default_zoom_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timelines_id'), 'timelines', ['id'], unique=False)
    op.create_index(op.f('ix_timelines_slug'), 'timelines', ['slug'], unique=True)
    op.create_table('timeline_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_summary', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('private_notes', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('WORK', 'EDUCATION', 'PROJECT', 'MILESTONE', 'CERTIFICATION', 'BLOG', name='nodetype'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('date_granularity', sa.Enum('EXACT', 'MONTH', 'YEAR', 'SEASON', name='dategranularity'), nullable=True),
    sa.Column('github_repo_id', sa.Integer(), nullable=True),
    sa.Column('github_pr_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['github_repo_id'], ['github_repositories.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['timeline_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_nodes_id'), 'timeline_nodes', ['id'], unique=False)
    op.create_table('node_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('media_data', sa.LargeBinary(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['timeline_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_artifacts_id'), 'node_artifacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_artifacts_id'), table_name='node_artifacts')
    op.drop_table('node_artifacts')
    op.drop_index(op.f('ix_timeline_nodes_id'), table_name='timeline_nodes')
    op.drop_table('timeline_nodes')
    op.drop_index(op.f('ix_timelines_slug'), table_name='timelines')
    op.drop_index(op.f('ix_timelines_id'), table_name='timelines')
    op.drop_table('timelines')
    # ### end Alembic commands ###
