name: "✨ Feature Request"
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please complete the details below.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature or enhancement.
      placeholder: "I would like to add..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful or necessary?
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you think this could be implemented.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Did you consider any alternative approaches?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, links, or anything else helpful.
